def union(G, H, rename=...): ...
def disjoint_union(G, H): ...
def intersection(G, H): ...
def difference(G, H): ...
def symmetric_difference(G, H): ...
def compose(G, H): ...
def full_join(G, H, rename=...): ...
