from collections.abc import Generator

from _typeshed import Incomplete

def dfs_edges(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
def dfs_tree(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
): ...
def dfs_predecessors(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
): ...
def dfs_successors(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
): ...
def dfs_postorder_nodes(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
): ...
def dfs_preorder_nodes(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
): ...
def dfs_labeled_edges(
    G, source: Incomplete | None = ..., depth_limit: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
