from _typeshed import Incomplete
from collections.abc import Generator
from typing import Any

FORWARD: Any = ...
REVERSE: Any = ...

def edge_dfs(G, source: Incomplete | None = ..., orientation: Incomplete | None = ...) -> Generator[Incomplete, None, Incomplete]: ...
