from collections.abc import Generator

from _typeshed import Incomplete

def weakly_connected_components(G) -> Generator[Incomplete, None, None]: ...
def number_weakly_connected_components(G): ...
def is_weakly_connected(G): ...
