from collections.abc import Generator, Mapping
from typing import Generic, TypeVar

from _typeshed import Incomplete

import networkx as nx

def k_components(G, min_density: float = ...): ...

_Node = TypeVar("_Node")

class _AntiGraph(nx.Graph[_Node], Generic[_Node]):
    all_edge_dict: Incomplete
    def single_edge_dict(self): ...
    edge_attr_dict_factory: Incomplete  # type: ignore
    def __getitem__(self, n): ...
    def neighbors(self, n): ...

    class AntiAtlasView(Mapping):
        def __init__(self, graph, node) -> None: ...
        def __len__(self): ...
        def __iter__(self): ...
        def __getitem__(self, nbr): ...

    class AntiAdjacencyView(AntiAtlasView):
        def __init__(self, graph) -> None: ...
        def __len__(self): ...
        def __iter__(self): ...
        def __getitem__(self, node): ...

    def subgraph(self, nodes): ...

    class AntiDegreeView(nx.reportviews.DegreeView):
        def __iter__(self): ...
        def __getitem__(self, n): ...

    degree: Incomplete
    def adjacency(self) -> Generator[Incomplete, None, None]: ...
