def treewidth_min_degree(G): ...
def treewidth_min_fill_in(G): ...
def min_fill_in_heuristic(graph): ...

class MinDegreeHeuristic:
    def __init__(self, graph) -> None: ...
    def best_node(self, graph): ...
