from _typeshed import Incomplete
from collections.abc import Generator

def naive_all_pairs_lowest_common_ancestor(
    G, pairs: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
def naive_lowest_common_ancestor(G, node1, node2, default: Incomplete | None = ...): ...
def tree_all_pairs_lowest_common_ancestor(
    G, root: Incomplete | None = ..., pairs: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
def lowest_common_ancestor(G, node1, node2, default: Incomplete | None = ...): ...
def all_pairs_lowest_common_ancestor(G, pairs: Incomplete | None = ...): ...
