from collections.abc import Generator

from _typeshed import Incomplete

def is_simple_path(G, nodes): ...
def all_simple_paths(G, source, target, cutoff: Incomplete | None = ...): ...
def all_simple_edge_paths(
    G, source, target, cutoff: Incomplete | None = ...
) -> Generator[Incomplete, None, Incomplete]: ...
def shortest_simple_paths(
    G, source, target, weight: Incomplete | None = ...
) -> Generator[Incomplete, None, Incomplete]: ...

class PathBuffer:
    paths: Incomplete
    sortedpaths: Incomplete
    counter: Incomplete
    def __init__(self) -> None: ...
    def __len__(self): ...
    def push(self, cost, path) -> None: ...
    def pop(self): ...
