from _typeshed import Incomplete

def index_satisfying(iterable, condition): ...
def is_tournament(G): ...
def hamiltonian_path(G): ...
def random_tournament(n, seed: Incomplete | None = ...): ...
def score_sequence(G): ...
def is_reachable(G, s, t): ...
def is_strongly_connected(G): ...
def tournament_matrix(G): ...
