from networkx import NetworkXError

class NotAPartition(NetworkXError):
    def __init__(self, G, collection) -> None: ...

def modularity(G, communities, weight: str = ..., resolution: int = ...): ...
def partition_quality(G, partition): ...
def inter_community_edges(G, partition): ...
