from _typeshed import Incomplete

def hits(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...): ...
def _hits_python(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...): ...
def _hits_numpy(G, normalized: bool = True): ...
def _hits_scipy(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...): ...
