from collections.abc import Generator

from _typeshed import Incomplete

def nonisomorphic_trees(
    order, create: str = ...
) -> Generator[Incomplete, None, None]: ...
def number_of_nonisomorphic_trees(order): ...
